// static const String home = '/home';
// static const String register = '/register';
// static const String aboutUs = '/about-us';
// static const String services = '/services';
// static const String contacts = '/contacts';
// static const String profile = '/profile';
// static const String footballers = '/footballers';
// static const String footballerForm = '/footballers/form';
// static const String contracts = '/contracts';
// static const String contractDetail = '/contracts/detail';
// static const String cases = '/cases';
// static const String caseDetail = '/cases/detail';
// static const String appointments = '/appointments';
// static const String appointmentDetail = '/appointments/detail';
// static const String appointmentForm = '/appointments/form';
// static const String documents = '/documents';
// static const String documentDetail = '/documents/detail';
// static const String documentUpload = '/documents/upload';
// static const String legalServices = '/legal-services';
// static const String consultancyForm = '/legal-services/consultancy';
// static const String representationForm = '/legal-services/representation';
// static const String footballerManagementForm = '/legal-services/footballer_management_form';


// home: (context) => const MainScreen(),
// aboutUs: (context) => const AboutUsScreen(),
// services: (context) => const ServicesScreen(),
// contacts: (context) => const ContactsScreen(),
// profile: (context) => const ProfileScreen(),
// footballers: (context) => const FootballersListScreen(),
// footballerForm: (context) => const FootballerFormScreen(),
// contracts: (context) => ContractsListScreen(),
// contractDetail: (context) => ContractDetailScreen(),
// cases: (context) => CasesListScreen(),
// // caseDetail: (context) => const CaseDetailScreen(),
// appointments: (context) => AppointmentsListScreen(),
// // appointmentDetail: (context) => const AppointmentDetailScreen(),
// appointmentForm: (context) => const AppointmentFormScreen(),
// documents: (context) => const DocumentsListScreen(),
// // documentDetail: (context) => const DocumentDetailScreen(),
// documentUpload: (context) => const DocumentUploadScreen(),
// legalServices: (context) => const LegalServicesListScreen(),
// consultancyForm: (context) => const ConsultancyFormScreen(),
// representationForm: (context) => const RepresentationFormScreen(),
// footballerManagementForm: (context) => const FootballerManagementFormScreen(),